In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("Final_Credit_Consumption_Cleaned.xlsx")

##### Seperating training data and predicting data

In [3]:
train_df = df[df["cc_cons"].notnull()]

predict_df = df[df["cc_cons"].isnull()]

In [4]:
train_df

,ID,account_type,gender,age,Income,Emp_Tenure_Years,Tenure_with_Bank,region_code,NetBanking_Flag,Avg_days_between_transaction,...,credit_count_jun,debit_count_jun,max_credit_amount_jun,loan_enq,emi_active,cc_cons,Avg_CC_Spend,Avg_DC_Spend,Total_CC_Transactions,Total_DC_Transactions
0,17051,current,M,30,MEDIUM,26.4,9,9,355,0,...,36,9,171200.0,Y,3448.84,16239.0000,7229.766667,20353.886667,40.0,21
1,11491,current,M,37,LOW,14.4,7,7,485,0,...,5,3,15694.0,Y,3812.69,39002.0000,18878.816667,2222.760000,79.0,19
2,7433,current,M,33,MEDIUM,3.2,1,1,764,0,...,7,58,28058.0,Y,9432.90,21182.0000,12594.898333,5680.180000,99.0,32
3,14606,current,M,63,LOW,10.2,6,6,863,0,...,12,0,24459.0,Y,144.61,8123.0000,6173.266667,9762.110000,35.0,78
4,8381,saving,M,33,MEDIUM,26.4,6,6,523,0,...,49,35,31574.0,Y,1887.89,28282.0000,13262.573333,4693.076667,15.0,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,6995,current,F,53,LOW,3.9,10,10,914,1,...,58,24,80688.0,Y,78966.76,8324.4592,13942.613333,7407.326667,34.0,29
14996,10376,current,M,44,MEDIUM,16.2,4,4,683,1,...,1,6,60164.0,Y,4762.10,3147.6088,6706.973333,2149.506667,116.0,108
14997,2181,current,M,37,MEDIUM,1.5,10,10,394,0,...,9,18,41702.0,Y,2877.33,11803.9860,20061.286667,9847.556667,149.0,151
14998,18417,current,M,220,MEDIUM,18.9,9,9,647,0,...,3,13,239.0,Y,13006.84,3640.4420,11346.080000,2040.060000,154.0,28
14999,4547,current,M,66,MEDIUM,8.0,4,4,536,1,...,9,1,31947.0,Y,1588.60,3500.7470,3686.591667,15880.986667,16.0,165

In [5]:
predict_df

,ID,account_type,gender,age,Income,Emp_Tenure_Years,Tenure_with_Bank,region_code,NetBanking_Flag,Avg_days_between_transaction,...,credit_count_jun,debit_count_jun,max_credit_amount_jun,loan_enq,emi_active,cc_cons,Avg_CC_Spend,Avg_DC_Spend,Total_CC_Transactions,Total_DC_Transactions
15000,17591,current,M,37,MEDIUM,11.9,4,4,575,1,...,3,12,25945.92,Y,1170.49,NaN,6027.533333,5815.166667,18.0,109
15001,13541,current,M,33,MEDIUM,7.8,6,6,394,0,...,6,39,12214.00,Y,16447.45,NaN,14007.543333,1686.640000,17.0,119
15002,13431,current,M,53,LOW,33.0,10,10,324,1,...,5,9,13215.00,Y,2622.28,NaN,3132.430000,3696.073333,42.0,53
15003,8687,current,M,33,MEDIUM,7.8,5,5,370,1,...,21,0,72317.00,Y,340.79,NaN,13709.920000,12859.000000,171.0,17
15004,14727,current,M,62,LOW,12.6,9,9,505,1,...,6,35,42344.00,Y,2812.20,NaN,3266.960000,3783.923333,59.0,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,12512,current,M,35,MEDIUM,13.5,1,1,523,0,...,21,50,58037.00,Y,7870.88,NaN,17464.370000,4091.193333,31.0,29
19996,14224,current,M,53,MEDIUM,9.9,7,7,723,1,...,62,38,24110.00,Y,3668.30,NaN,9749.816667,3228.033333,143.0,77
19997,18740,current,M,62,HIGH,37.8,8,8,863,1,...,2,18,1769.00,Y,5450.34,NaN,4909.131667,5352.680000,90.0,20
19998,18134,current,M,34,MEDIUM,12.6,4,4,882,0,...,117,64,37255.00,Y,59.29,NaN,13399.753333,14353.666667,72.0,112
19999,12413,current,M,27,LOW,3.5,8,8,447,1,...,9,64,96213.00,Y,793.41,NaN,10121.546667,7537.333333,92.0,55

In [6]:
X = train_df.drop(
    columns=["ID","cc_cons"]
)

y = train_df["cc_cons"]

In [7]:
X

,account_type,gender,age,Income,Emp_Tenure_Years,Tenure_with_Bank,region_code,NetBanking_Flag,Avg_days_between_transaction,cc_cons_apr,...,credit_amount_jun,credit_count_jun,debit_count_jun,max_credit_amount_jun,loan_enq,emi_active,Avg_CC_Spend,Avg_DC_Spend,Total_CC_Transactions,Total_DC_Transactions
0,current,M,30,MEDIUM,26.4,9,9,355,0,2017.46,...,80959.00,36,9,171200.0,Y,3448.84,7229.766667,20353.886667,40.0,21
1,current,M,37,LOW,14.4,7,7,485,0,7687.00,...,495080.00,5,3,15694.0,Y,3812.69,18878.816667,2222.760000,79.0,19
2,current,M,33,MEDIUM,3.2,1,1,764,0,9094.46,...,115707.38,7,58,28058.0,Y,9432.90,12594.898333,5680.180000,99.0,32
3,current,M,63,LOW,10.2,6,6,863,0,3126.00,...,63606.00,12,0,24459.0,Y,144.61,6173.266667,9762.110000,35.0,78
4,saving,M,33,MEDIUM,26.4,6,6,523,0,24988.72,...,62353.35,49,35,31574.0,Y,1887.89,13262.573333,4693.076667,15.0,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,current,F,53,LOW,3.9,10,10,914,1,6045.34,...,349670.00,58,24,80688.0,Y,78966.76,13942.613333,7407.326667,34.0,29
14996,current,M,44,MEDIUM,16.2,4,4,683,1,5387.00,...,131979.75,1,6,60164.0,Y,4762.10,6706.973333,2149.506667,116.0,108
14997,current,M,37,MEDIUM,1.5,10,10,394,0,9577.00,...,8005.00,9,18,41702.0,Y,2877.33,20061.286667,9847.556667,149.0,151
14998,current,M,220,MEDIUM,18.9,9,9,647,0,5305.84,...,69191.43,3,13,239.0,Y,13006.84,11346.080000,2040.060000,154.0,28
14999,current,M,66,MEDIUM,8.0,4,4,536,1,5140.00,...,35138.95,9,1,31947.0,Y,1588.60,3686.591667,15880.986667,16.0,165

In [8]:
y

0        16239.0000
1        39002.0000
2        21182.0000
3         8123.0000
4        28282.0000
            ...
14995     8324.4592
14996     3147.6088
14997    11803.9860
14998     3640.4420
14999     3500.7470
Name: cc_cons, Length: 15000, dtype: float64

##### Checking the categorical values

In [9]:
print(
    X.select_dtypes(
        include="object"
    ).columns
)

Index(['account_type', 'gender', 'Income', 'loan_enq'], dtype='str')

/tmp/ipykernel_27237/2057143280.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  X.select_dtypes(

##### Converting categorical values into the numerical values using the LabelEncoder

In [10]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in X.select_dtypes(include="object").columns:
    X[col] = le.fit_transform(X[col].astype(str))

/tmp/ipykernel_27237/2494061571.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in X.select_dtypes(include="object").columns:

##### Spliting the data into training data and testing data

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [15]:
# Check missing values in X
print(X.isnull().sum()[X.isnull().sum() > 0])

Series([], dtype: int64)

In [16]:
# Separate numerical and categorical columns
num_cols = X.select_dtypes(include=["int64", "float64"]).columns
cat_cols = X.select_dtypes(include=["object"]).columns

# Fill numerical missing values with median
for col in num_cols:
    X[col] = X[col].fillna(X[col].median())

# Fill categorical missing values with mode
for col in cat_cols:
    X[col] = X[col].fillna(X[col].mode()[0])

In [19]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(
    X_train,
    y_train
)

LinearRegression()

In [20]:
y_pred = lr.predict(X_test)

In [21]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

mae = mean_absolute_error(
    y_test,
    y_pred
)

rmse = mean_squared_error(
    y_test,
    y_pred
) ** 0.5

r2 = r2_score(
    y_test,
    y_pred
)

print("MAE:",mae)
print("RMSE:",rmse)
print("R2:",r2)

MAE: 1866.8082413737955
RMSE: 2608.5086593080796
R2: 0.8645270953758972

In [22]:
from sklearn.tree import DecisionTreeRegressor

dt = DecisionTreeRegressor(
    random_state=42
)

dt.fit(
    X_train,
    y_train
)

dt_pred = dt.predict(X_test)

In [23]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf.fit(
    X_train,
    y_train
)

rf_pred = rf.predict(X_test)

In [25]:
from sklearn.metrics import r2_score

y_pred = lr.predict(X_test)

lr_r2 = r2_score(y_test, y_pred)

print("Linear Regression R2:", lr_r2)

Linear Regression R2: 0.8645270953758972

In [26]:
dt_pred = dt.predict(X_test)

dt_r2 = r2_score(y_test, dt_pred)

print("Decision Tree R2:", dt_r2)

Decision Tree R2: 0.6565547721580884

In [27]:
rf_pred = rf.predict(X_test)

rf_r2 = r2_score(y_test, rf_pred)

print("Random Forest R2:", rf_r2)

Random Forest R2: 0.8481062465934442

In [28]:
results = pd.DataFrame({
    "Model":[
        "Linear Regression",
        "Decision Tree",
        "Random Forest"
    ],
    "R2":[
        lr_r2,
        dt_r2,
        rf_r2
    ]
})

print(results)

               Model        R2
0  Linear Regression  0.864527
1      Decision Tree  0.656555
2      Random Forest  0.848106

In [29]:
importance = pd.DataFrame({
    "Feature":X.columns,
    "Importance":rf.feature_importances_
})

importance.sort_values(
    by="Importance",
    ascending=False
).head(10)

              Feature  Importance
47       Avg_CC_Spend    0.648777
48       Avg_DC_Spend    0.137663
12        dc_cons_may    0.051455
14        dc_cons_jun    0.022095
10        dc_cons_apr    0.021030
11        cc_cons_may    0.013871
46         emi_active    0.004061
30   debit_amount_apr    0.003968
32    debit_count_apr    0.003923
41  credit_amount_jun    0.003890

In [30]:
predict_X = predict_df.drop(
    columns=["ID","cc_cons"]
)

In [34]:
rf

RandomForestRegressor(random_state=42)

In [35]:
predict_X = predict_df.drop(
    columns=["ID", "cc_cons"]
)

In [36]:
for col in predict_X.select_dtypes(include="object").columns:
    predict_X[col] = le.fit_transform(
        predict_X[col].astype(str)
    )

/tmp/ipykernel_27237/3090042859.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in predict_X.select_dtypes(include="object").columns:

In [37]:
future_predictions = rf.predict(predict_X)

In [38]:
predict_df["Predicted_cc_cons"] = future_predictions

In [39]:
predict_df.to_excel(
    "Predicted_Credit_Consumption.xlsx",
    index=False
)